[toolchain]
anchor_version = "1.0.2"

[features]
resolution = true
skip-lint = false

[programs.devnet]
quivo = "BgUU6i94wtZrx215bGBRZePEDXTYC4snNrbDEymVcCVG"

[programs.localnet]
quivo = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --manifest-path programs/quivo/Cargo.toml --lib"

[hooks]
